veginner/Post/urls.py
from . import views
from django.urls import path
import django.views.defaults

urlpatterns = [
    path('about', views.about, name='about'),
    path('community', views.community, name='community'),
#     path('community/detail/', views.detail, name='detail'),
    path('community/detail/<int:post_id>/', views.detail, name='detail'),
    path('community/update/<int:post_id>/', views.update, name='update'),
    path('community/delete/<int:post_id>/', views.delete, name='delete'),
    path('ajaxlike', views.ajaxlike, name='ajaxlike'),
#     path('404', django.views.defaults.page_not_found),
]

veginner/veginner/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from User.views import CustomPasswordChangeView
from django.views.static import serve
from django.urls import re_path

urlpatterns = [
    # admin
    url('^admin/', admin.site.urls),
    # user app
    path('', include('User.urls')),
    path('', include('Post.urls')),
    path('', include('Mypage.urls')),


    # allauth.
    path(
        'email-confirmation-done/',
        TemplateView.as_view(template_name='account.email_confirmation_done.html'),
        name='account_email_confirmation_done'
    ),
    path(
        'password/change/',
        CustomPasswordChangeView.as_view(),
        name='account_password_change'
    ),
    path('', include('allauth.urls')),
#
#
#     # media, static setting
#     re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    ]

# django 기본 제공 템플릿 view를 사용하면 따로 views.py에서 정의 안 ㅎ해 줘도 되어서 걍 렌더링만 해 줄 거라
# 그냥 템플릿 뷰로 썼습니다 26번 라인

veginner/Post/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime

from django.db import models
from django.db.models.fields.related import ForeignKey
from django.db.models.fields import CharField, TextField
from django.urls import reverse
from User.models import User


# Create your models here.
class Vegan_type(models.Model):
    vegan_id = models.AutoField(primary_key=True)
    vegan_type = models.CharField(max_length=20, verbose_name='비건 타입', null=False)
    def __str__(self):
        return str(self.vegan_type) + ' ' + str(self.vegan_id)
    class Meta:
        db_table = 'Vegan_type'
        verbose_name = '비건 타입'
        verbose_name_plural = '비건 타입'


class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자')
    date = models.DateField(default=datetime.date.today, verbose_name='작성 날짜')
    food_name = models.CharField(max_length=50, verbose_name='음식 이름', null=False)
    post_vegan_type = models.ForeignKey(Vegan_type, on_delete=models.CASCADE, verbose_name='비건 종류', null=False)
    image = models.ImageField(null=False, verbose_name='음식 사진', upload_to='')
    content = TextField(verbose_name='내용')
    write_time = models.DateTimeField(auto_now_add=True, verbose_name="작성 시간")
    like = models.ManyToManyField(User, related_name='likes', blank=True)
    @property
    def like_count(self):
        return self.like.count() # like 컬럼의 값의 갯수를 센다
    def __str__(self):
        return str(self.post_id) + ' ' + str(self.writer)
    class Meta:
        db_table = 'Post'
        verbose_name = '포스트'
        verbose_name_plural = '포스트'

veginner/Post/forms.py
from django import forms
import datetime
from django.forms.widgets import NumberInput

POST_SORT_CHOICES = [
    ("Vegan", "Vegan"),
    ("Lacto", "Lacto"),
    ("Ovo", "Ovo"),
    ("Lacto-Ovo", "Lacto-Ovo"),
    ("Pesco", "Pesco"),
    ("Pollo", "Pollo"),
    ("Flexitarian", "Flexitarian")
    ]


class PostForm(forms.Form):
    date = forms.DateField(initial=datetime.date.today(), widget=NumberInput(attrs={'type': 'date'}), label='date', required=True)
    food_name = forms.CharField(max_length=50, label='food_name', required=True)
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':4}), label='content', required=True)
    post_vegan_type = forms.ChoiceField(choices=POST_SORT_CHOICES, label='post_vegan_type', required=True)
    image = forms.ImageField(label='image', required=True)

    def clean(self):
        now = datetime.date.today()
        form_data = self.cleaned_data
        if now < form_data["date"]:
            raise forms.ValidationError("오늘 날짜까지 입력할 수 있습니다.")
        if 'date' in self._errors:
            raise forms.ValidationError("date 에러")
        if 'food_name' in self._errors:
            raise forms.ValidationError("food_name 에러")
        if 'content' in self._errors:
            raise forms.ValidationError("content 에러")
        if 'post_vegan_type' in self._errors:
            raise forms.ValidationError("post_vegan_type 에러")
        if 'image' in self._errors:
            raise forms.ValidationError("image 에러")
        return form_data

veginner/Post/views.py
from __future__ import unicode_literals
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import Vegan_type, Post
from User.models import User
from .forms import PostForm
import sweetify
import datetime
import os
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.sessions.models import Session
from django.db.models import Count
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.http.response import JsonResponse
try:
    from django.utils import simplejson as json
except ImportError:
    import json

# Create your views here.
def community(req):
    if req.method == 'POST':
        print("community post 들어옴")
        form = PostForm(req.POST, req.FILES)
        if form.is_valid():
            post = Post()
            post.writer = User.objects.get(nickname=req.POST.get("writer"))
            post.date = form.cleaned_data["date"]
            post.food_name = form.cleaned_data["food_name"]
            post.post_vegan_type = Vegan_type.objects.get(vegan_type=form.cleaned_data["post_vegan_type"])
            post.image = form.cleaned_data["image"]
            post.content = form.cleaned_data["content"]
            post.save()
            print("폼저장")

        else:
            print("유효성 또 실패")
            sweetify.warning(req, form.non_field_errors(), timer=1200)
        return redirect('community')
    else:
        form = PostForm()
        sort = req.GET.get('sort', '')# sorting
        order = req.GET.get('order', '')# ordering
        page = req.GET.get('page', '')# pagination
        post_value = Post.objects.values('post_id', 'writer__nickname', 'food_name', 'post_vegan_type__vegan_type', 'write_time', 'image', 'content').annotate(like_count=Count('like'))
        posts = post_value.annotate(like_count=Count('like')).order_by('-write_time')# default posts
        vegan_type_dict = dict()
        for obj in Vegan_type.objects.all():
            vegan_type_dict[obj.vegan_type] = [obj.vegan_id]
            if obj.vegan_type == "Lacto-Ovo":
                vegan_type_dict[obj.vegan_type] = [9, 10, 11]
        if sort != '' and order != '':
            if order == 'Likes':
                posts = post_value.filter(post_vegan_type__in=vegan_type_dict[sort]).order_by('-like_count','-write_time')
            else:
                posts = post_value.filter(post_vegan_type__in=vegan_type_dict[sort]).order_by('-write_time')
        elif sort != '' and order == '':
            posts = post_value.filter(post_vegan_type__in=vegan_type_dict[sort]).order_by('-write_time')
        elif sort == '' and order != '':
            if order == 'Likes':
                posts = post_value.order_by('-like_count','-write_time')
            else:
                posts = post_value.order_by('-write_time')
        paginator = Paginator(posts, 12)
        post_list = paginator.get_page(page)
        mySession = req.session.session_key
        if mySession == None:
            me_like = {}
        else:
            me_like = Post.objects.values('post_id').filter(like__user_id=req.user.user_id)
        me_like_list = []
        for m in me_like:
            me_like_list.append(m['post_id'])
        context = {
            "post": post_list,
            "form": form,
            "me_like_list": me_like_list
        }
        return render(req, 'Post/community.html', context)

# 좋아요 뷰
@require_POST
@login_required
def ajaxlike(req):
    if req.method == 'POST':
        user = req.user
        posting_id = req.POST.get('pk', None)
        post = Post.objects.get(post_id=posting_id)
        print(post)
        if post.like.filter(user_id=user.user_id).exists():
            post.like.remove(user)
            message = "좋아요를 취소하였습니다"
            state = "cancel"
        else:
            post.like.add(user)
            message = "좋아요 완료"
            state = "like"
    print(state)
    context = {
        'likes_count': post.like_count,
        'message': message,
        'state': state
        }
    return JsonResponse(context)

# about 페이지
def about(req):
    return render(req, 'Post/about.html')

# 게시글 detail
def detail(req,post_id):
    post_detail = get_object_or_404(Post, pk=post_id)
    return render(req, 'Post/detail.html', {'post': post_detail})

# 게시글 삭제
def delete(req,post_id):
    selected_post = Post.objects.get(post_id=post_id)
    if os.path.join(selected_post.image.path):
        os.remove(os.path.join(selected_post.image.path))
        selected_post.delete()
        return redirect("community")
    else:
        print("The file does not exist")
        return redirect("detail",post_id)

# 게시글 수정
def update(req,post_id):
    update_post = Post.objects.get(post_id = post_id)
    if req.method == "POST":
        update_post.date = req.POST['date']
        update_post.food_name = req.POST['food_name']
        update_post.content = req.POST["content"]
        update_post.post_vegan_type = Vegan_type.objects.get(vegan_type=req.POST["post_vegan_type"])
        update_post.save()
        return redirect('detail',post_id)

    else:
        update_postForm = PostForm
        context = {
                'form': update_postForm,
                'post': update_post
            }
        return render(req, 'Post/detail.html', context)

veginner/templates/Post/detail.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block contents %}

<section class="container">

    {% if form %}
    <div class="mypage-header d-flex justify-content-between mt-5">
        <h3>EDIT</h3>
    </div>

    <div class="p-3 community_header text-white rounded-top">
        <h2 class="modal-title">Veginner {{post.writer.nickname}}</h2>
    </div>

    <form enctype="multipart/form-data" id="post_submit" method="post">
        <div class="p-3 border border-top-0 rounded-bottom">
            {% csrf_token %}

            <div class="mb-3">
                <div class="d-flex justify-content-center flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0 mt-2">
                        <i class="fas fa-calendar-check fa-lg me-1 fa-fw"></i>
                        <label class="form-label mb-2">섭취일</label>
                        <div>
                            {{ form.date|attr:"class:floatingInput form-control"|attr:"id:date"}}
                        </div>

                        <script>
                            function formatDate(date) {
                                var year = date.slice(0, 4);
                                var month = date.slice(6, 8);
                                month = month.replace(/\s/g, "");
                                var day = date.slice(9, 11);
                                day = day.replace(/\s/g, "");

                                if (month.length < 2)
                                    month = '0' + month;
                                if (day.length < 2)
                                    day = '0' + day;

                                var date = year + '-' + month + '-' + day;

                                return date;
                            }

                            document.getElementById('date').value = formatDate('{{post.date}}');
                        </script>
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0 mt-2">
                        <i class="fas fa-utensils fa-lg me-1 fa-fw"></i>
                        <label class="form-label" for="floatingInput">음식 이름</label>
                        {{ form.food_name|attr:"class:floatingInput form-control"|attr:"id:food_name"}}
                        <script>
                            document.getElementById('food_name').setAttribute('value', "{{post.food_name}}");
                        </script>
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">
                        <i class="fas fa-sticky-note fa-lg me-1 fa-fw"></i>
                        <label class="form-label" for="floatingInput">내용</label>
                        <textarea class="form-control" cols="40" id="content" name="content"
                                  rows="4">{{ post.content }}</textarea>
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <div class="row d-flex flex-row align-items-center mb-4">
                    <div class="col-6 form-outline">
                        <label class="form-label" for="floatingInput">
                            <i class="fas fa-leaf fa-lg me-1 fa-fw"></i>비건 유형
                            <span data-placement="top" data-toggle="tooltip"
                                  title="Vegan: 채소, Lacto: 우유, Ovo: 계란, Lacto-Ovo: 우유&계란, Pesco: 생선, Pollo: 닭, Flexitarian: 육식">
                                            <i class="modal-info-icon fas fa-info-circle"></i>
                                        </span>
                        </label>
                        {{ form.post_vegan_type|attr:"class:floatingInput form-control"|attr:"id:vegan_type"}}

                        <script>
                            $(function () {
                                $('[data-toggle="tooltip"]').tooltip()
                            })
                        </script>
                        <script>
                            document.getElementById('vegan_type').setAttribute('value', "{{post.post_vegan_type.vegan_type}}");
                            $('#vegan_type').val('{{post.post_vegan_type.vegan_type}}').prop("selected", true);
                        </script>
                    </div>
                </div>
            </div>

            <div>
                <img class="mb-4" src="{{ post.image.url }}" style="height: 500px; width: 500px; display: block;">
            </div>
        </div>

        <div class="py-2 text-end mb-5">
            <button class="btn btn-secondary m-1" onclick="location.href='../../detail/{{ post.post_id }}'"
                    type="button">CANCEL
            </button>
            <button class="btn detail-edit-btn m-1" type="submit">POST</button>
        </div>
    </form>

    {% else %}
    <div class="mypage-header d-flex justify-content-between mt-5">
        <h3>DETAIL</h3>
    </div>

    <div>
        <div class="p-3 community_header text-white rounded-top">
            <h2 class="modal-title">Veginner {{post.writer.nickname}}</h2>
        </div>

        <div class="p-3 border border-top-0 rounded-bottom">

            <div class="mb-3">
                <div class="d-flex justify-content-center flex-row align-items-center mb-4">
                    <div class="flex-fill mb-0 mt-2">
                        <i class="fas fa-utensils fa-lg me-1 fa-fw"></i>
                        <label class="mb-2">섭취일</label>
                        <div class="border rounded-2 py-2 px-3">
                            {{ post.date }}
                        </div>
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <div class="d-flex flex-row align-items-center mb-4">
                    <div class="flex-fill mb-0 mt-2">
                        <i class="fas fa-cookie-bite fa-lg me-1 fa-fw"></i>
                        <label class="mb-2">음식 이름</label>
                        <div class="border rounded-2 py-2 px-3">
                            {{ post.food_name }}
                        </div>
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <div class="d-flex flex-row align-items-center mb-4">
                    <div class="flex-fill mb-0">
                        <i class="fas fa-sticky-note fa-lg me-1 fa-fw"></i>
                        <label class="mb-2">내용</label>
                        <textarea class="floatingInput form-control" cols="40" id="id_content" name="content" readonly
                                  required rows="4">{{ post.content|safe }}</textarea>
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <div class="d-flex flex-row align-items-center mb-4">
                    <div class="flex-fill mb-0">
                        <i class="fas fa-leaf fa-lg me-1 fa-fw"></i>
                        <label class="mb-2">비건 유형
                            <span data-placement="top" data-toggle="tooltip"
                                  title="Vegan: 채소, Lacto: 우유, Ovo: 계란, Lacto-Ovo: 우유&계란, Pesco: 생선, Pollo: 닭, Flexitarian: 육식">
                                        <i class="modal-info-icon fas fa-info-circle"></i>
                                    </span>

                            <script>
                                $(function () {
                                    $('[data-toggle="tooltip"]').tooltip()
                                })
                            </script>
                        </label>
                        <div class="border rounded-2 py-2 px-3">
                            {{ post.post_vegan_type.vegan_type}}
                        </div>
                    </div>
                </div>

            </div>

            <div>
                <img class="mb-4" src="{{ post.image.url }}" style="height: 500px; width: 500px; display: block;">
            </div>
        </div>

        <div class="py-2 text-end mb-5">

            {% if user == post.writer %}
            <a href="{% url 'update' post.post_id %}">
                <button class="detail-edit-btn btn m-1" type="button">EDIT</button>
            </a>
            <button class="detail-delete-btn btn" onclick="alert_del();" type="button">DELETE</button>

            <script>
                function alert_del() {
                    var alert = confirm('게시글을 정말로 삭제하시겠습니까?');
                    if (alert) {
                        window.location.href = "{% url 'delete' post.post_id %}"
                        alert("성공적으로 삭제되었습니다.");
                    }
                }
            </script>

            {% endif %}
            <a href="{% url 'community' %}">
                <button class="btn btn-secondary m-1" id="post_btn" type="button">CLOSE</button>
            </a>
        </div>
    </div>
    {% endif %}
</section>

{% endblock contents %}